[[redirects]]
  from = "https://floridieunfilm.com/*"
  to = "https://floridieun.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.floridieunfilm.com/*"
  to = "https://floridieun.com/:splat"
  status = 301
  force = true
